use std::env;
use std::error::Error;
use std::path::{Path, PathBuf};
use std::process::{Command, ExitStatus};

const ANTLR4_JAR: &str = "antlr4-4.8-2-SNAPSHOT-complete.jar";

fn main() {
    let grammars = vec![
        "CSV",
        "ReferenceToATN",
        "XMLLexer",
        "SimpleLR",
        "Labels",
        "FHIRPath",
    ];
    let additional_args = vec![Some("-visitor"), None, None, None, None];
    let antlr_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tools")
        .join(ANTLR4_JAR);

    if !antlr_path.exists() {
        fetch_antlr4_rust_jar(&antlr_path).expect("Failed to download ANTLR4 jar for Rust");
    }

    for (grammar, arg) in grammars.into_iter().zip(additional_args) {
        //ignoring error because we do not need to run anything when deploying to crates.io
        let _ = gen_for_grammar(grammar, &antlr_path, arg);
    }

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", antlr_path.display());
}

/// Fetches the ANTLR4 jar for Rust code generation. from github.com/rrevenantt/antlr4rust
fn fetch_antlr4_rust_jar(antlr_path: &Path) -> std::io::Result<ExitStatus> {
    let download_url = format!("https://github.com/rrevenantt/antlr4rust/releases/download/antlr4-4.8-2-Rust-0.2/{ANTLR4_JAR}");

    eprintln!(
        "#####\nDownloading ANTLR4:\n  curl -L '{download_url}' -o {}\n#####",
        antlr_path.display()
    );
    std::process::Command::new("curl")
        .arg("-L")
        .arg(&download_url)
        .arg("-o")
        .arg(&antlr_path)
        .spawn()
        .expect("failed to create antlr directory")
        .wait()
}

fn gen_for_grammar(
    grammar_file_name: &str, antlr_path: &Path, additional_arg: Option<&str>,
) -> Result<(), Box<dyn Error>> {
    let dest_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("gen");
    let input = env::current_dir().unwrap().join("grammars");
    let file_name = grammar_file_name.to_owned() + ".g4";

    Command::new("java")
        .current_dir(input)
        .arg("-cp")
        .arg(antlr_path)
        .arg("org.antlr.v4.Tool")
        .arg("-Dlanguage=Rust")
        .arg("-o")
        .arg(&dest_path)
        .arg(&file_name)
        .args(additional_arg)
        .spawn()
        .expect("antlr tool failed to start")
        .wait_with_output()?;

    let generated_file = &file_name
        .to_lowercase()
        .replace("lexer", "")
        .replace(".g4", "lexer.rs");

    let generated_file_path = dest_path.join(&generated_file);
    if !generated_file_path.exists() {
        eprintln!(
            "The file `{generated_file}` was not generated by the grammar `{file_name}` at `{}`",
            dest_path.display()
        );
        std::process::exit(-2);
    }

    // cargo fmt the generated file
    Command::new("cargo")
        .arg("fmt")
        .arg("--")
        .arg(generated_file_path)
        .spawn()
        .expect("failed to format generated file")
        .wait()?;

    println!("cargo:rerun-if-changed=grammars/{}", file_name);
    Ok(())
}
